import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALDI
 */
public class PBOII extends javax.swing.JFrame {
    int i9, i7, i5, i3, diskon,biayatambahan, harga,jumlahbarang, total,totaldiskon, bayar, kembali;
    
    public void selectData() {
String kolom[] = {"Nama Pembeli","Merk Laptop","Processor","Jumlah Beli","Total Diskon","Total"};
DefaultTableModel dtm = new DefaultTableModel(null, kolom);
String Cari = txt_cari.getText(); 
String SQL = "SELECT * FROM data_laptop WHERE NamaPembeli LIKE '%"+Cari+"%'";
rs = KoneksiDB.executeQuery(SQL);
try {
        while(rs.next()) {
        String NamaPembeli = rs.getString(1);
        String Merk = rs.getString(2);
        String Processor = rs.getString(3);
        String JumlahBeli = rs.getString(4);
        String TotalDiskon = rs.getString(5);
        String Total = rs.getString(6);    
    String data[] = {NamaPembeli,Merk,Processor,JumlahBeli,TotalDiskon,Total};
    dtm.addRow(data);
        }
    } catch (SQLException ex) {
      Logger.getLogger(PBOII.class.getName()).log(Level.SEVERE, null, ex);
      }
      Tbl_Data.setModel(dtm);
    }
        
   
    /**
     * Creates new form PBOII
     */
    public PBOII() {
        initComponents();
        selectData();
    }
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        txt_pembeli = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txt_totalbarang = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        txt_totaldiskon = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        txt_jumlahbarang = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Data = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel62 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btn_delete = new javax.swing.JButton();
        cbo_processor = new javax.swing.JComboBox<>();
        jLabel75 = new javax.swing.JLabel();
        cbo_merk = new javax.swing.JComboBox<>();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txt_cari = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        cbo_jenisbayar = new javax.swing.JComboBox<>();

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form_A");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel10.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel10.setPreferredSize(new java.awt.Dimension(1170, 485));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel63.setText(":");
        jPanel10.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 20, -1));

        txt_pembeli.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        txt_pembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pembelitxt_pembeliActionPerformed(evt);
            }
        });
        jPanel10.add(txt_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, -1));
        jPanel10.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel64.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel10.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, -1, -1));

        jLabel65.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel65.setText("Processor");
        jPanel10.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel66.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel66.setText("Jenis Bayar");
        jPanel10.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel67.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel67.setText("Harga");
        jPanel10.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        txt_harga.setEditable(false);
        txt_harga.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargatxt_hargaActionPerformed(evt);
            }
        });
        jPanel10.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));

        jPanel9.setBackground(new java.awt.Color(0, 204, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel68.setText("Total Diskon");
        jPanel9.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txt_diskon.setEditable(false);
        txt_diskon.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        txt_diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskontxt_diskonActionPerformed(evt);
            }
        });
        jPanel9.add(txt_diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, -1));

        jLabel70.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel70.setText("Diskon");
        jPanel9.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel71.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel71.setText("Total Barang");
        jPanel9.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txt_totalbarang.setEditable(false);
        txt_totalbarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jPanel9.add(txt_totalbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 130, -1));

        btn_next.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btn_next.setText("NEXT");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextbtn_nextActionPerformed(evt);
            }
        });
        jPanel9.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 90, -1));

        btn_exit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitbtn_keluarActionPerformed(evt);
            }
        });
        jPanel9.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, -1));

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totaltxt_totalActionPerformed(evt);
            }
        });
        jPanel9.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, -1));

        jLabel72.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel72.setText("Total");
        jPanel9.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        txt_totaldiskon.setEditable(false);
        txt_totaldiskon.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jPanel9.add(txt_totaldiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 180, -1));

        jLabel82.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel82.setText(":");
        jPanel9.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 20, -1));

        jLabel83.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel83.setText(":");
        jPanel9.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 20, -1));

        jLabel84.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel84.setText(":");
        jPanel9.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 20, -1));

        jLabel85.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel85.setText(":");
        jPanel9.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 20, -1));

        jLabel74.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel74.setText("UNIT");
        jPanel9.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel79.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel79.setText("Rp.");
        jPanel9.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 30, -1));

        jLabel90.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel90.setText("Rp.");
        jPanel9.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 30, -1));

        jLabel91.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel91.setText("Rp.");
        jPanel9.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 30, -1));

        btn_clear.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearbtn_beliActionPerformed(evt);
            }
        });
        jPanel9.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 90, -1));

        jLabel76.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel76.setText("Pembayaran");
        jPanel9.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel10.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 530, 190));

        jLabel73.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel73.setText("Jumlah Barang");
        jPanel10.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txt_jumlahbarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        txt_jumlahbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahbarangtxt_jumlahbarangActionPerformed(evt);
            }
        });
        jPanel10.add(txt_jumlahbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 130, -1));

        jLabel77.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel77.setText("Nama Pembeli");
        jPanel10.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel78.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel78.setText(":");
        jPanel10.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 20, -1));

        jLabel80.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel80.setText(":");
        jPanel10.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 20, -1));

        jLabel86.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel86.setText(":");
        jPanel10.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 20, -1));

        jLabel87.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel87.setText(":");
        jPanel10.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 20, -1));

        jLabel88.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel88.setText("/UNIT");
        jPanel10.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel89.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel10.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        jLabel92.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel92.setText("Rp.");
        jPanel10.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 30, -1));

        btn_refresh.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshbtn_beliActionPerformed(evt);
            }
        });
        jPanel10.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 100, -1));

        Tbl_Data.setBackground(new java.awt.Color(0, 204, 255));
        Tbl_Data.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        Tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pembeli", "Merk Laptop", "Processor", "Jumlah Barang", "Diskon", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tbl_Data);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 580, 180));

        panel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel62.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        jLabel62.setText("ALDIE LAPTOP STORE");
        panel1.add(jLabel62);

        jPanel10.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1150, 60));

        btn_add.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addbtn_nextActionPerformed(evt);
            }
        });
        jPanel10.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 90, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 600, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 230, 10, 240));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 30, 240));

        btn_delete.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletebtn_beliActionPerformed(evt);
            }
        });
        jPanel10.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 100, -1));

        cbo_processor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        cbo_processor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Processor", "Intel Core i3", "Intel Core i5", "Intel Core i7", "Inyel Core i9" }));
        cbo_processor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_processorActionPerformed(evt);
            }
        });
        cbo_processor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbo_processorKeyReleased(evt);
            }
        });
        jPanel10.add(cbo_processor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, -1));

        jLabel75.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel75.setText("Merk");
        jPanel10.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cbo_merk.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        cbo_merk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Merk", "Acer", "Asus", "Lenovo" }));
        cbo_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_merkActionPerformed(evt);
            }
        });
        cbo_merk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbo_merkKeyReleased(evt);
            }
        });
        jPanel10.add(cbo_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, -1));

        jLabel93.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel93.setText("UNIT");
        jPanel10.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel94.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel10.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel95.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel10.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 600, 20));

        txt_cari.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        jPanel10.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 242, 130, 30));

        jLabel69.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel10.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        jLabel96.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel96.setText(":");
        jPanel10.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 20, -1));

        cbo_jenisbayar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        cbo_jenisbayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembayaran", "Cash", "Transfer" }));
        cbo_jenisbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_jenisbayarActionPerformed(evt);
            }
        });
        cbo_jenisbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbo_jenisbayarKeyReleased(evt);
            }
        });
        jPanel10.add(cbo_jenisbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, -1));

        getContentPane().add(jPanel10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pembelitxt_pembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pembelitxt_pembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pembelitxt_pembeliActionPerformed

    private void txt_hargatxt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargatxt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargatxt_hargaActionPerformed

    private void txt_diskontxt_diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskontxt_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diskontxt_diskonActionPerformed

    private void btn_nextbtn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextbtn_nextActionPerformed
        // TODO add your handling code here:
        if (cbo_jenisbayar.getSelectedItem().equals("Cash"))
        {
            Cash Form_B = new Cash(txt_total.getText());
            Form_B.setVisible(true);
            this.dispose();
        }
        else
        if (cbo_jenisbayar.getSelectedItem().equals("Transfer"))
        {
            Transfer Form_C = new Transfer(txt_total.getText());
            Form_C.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_nextbtn_nextActionPerformed

    private void btn_exitbtn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitbtn_keluarActionPerformed
        // TODO add your handling code here:
        int   answare = JOptionPane.showConfirmDialog(null,"Yakin Ingin Keluar?","Selesai",
            JOptionPane.OK_OPTION);
        if(answare==JOptionPane.OK_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_btn_exitbtn_keluarActionPerformed

    private void txt_totaltxt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totaltxt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totaltxt_totalActionPerformed

    private void txt_jumlahbarangtxt_jumlahbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahbarangtxt_jumlahbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahbarangtxt_jumlahbarangActionPerformed

    private void btn_clearbtn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearbtn_beliActionPerformed
        // TODO add your handling code here:
            txt_pembeli.setText("");
            cbo_merk.setSelectedItem("Pilih Merk");
            cbo_processor.setSelectedItem("Pilih Processor");
            txt_harga.setText("");
            cbo_jenisbayar.setSelectedItem("Piih Pembayaran");
            txt_diskon.setText("");
            txt_totaldiskon.setText("");
            txt_total.setText("");
            txt_pembeli.requestFocus();
            txt_jumlahbarang.setText("");
            txt_totalbarang.setText("");
    }//GEN-LAST:event_btn_clearbtn_beliActionPerformed

    private void btn_addbtn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addbtn_nextActionPerformed
        // TODO add your handling code here:      
    if ("".equals(txt_pembeli.getText()) || "".equals(cbo_merk.getSelectedItem()) || "".equals(cbo_processor.getSelectedItem()) || "".equals(txt_jumlahbarang.getText()) || "".equals(txt_diskon.getText()) || "".equals(cbo_jenisbayar.getSelectedItem())|| "".equals(txt_total.getText())) {
    JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
    } else {
        
            String SQL = "INSERT INTO `data_laptop` (`NamaPembeli`, `MerkLaptop`, `Processor`, `JumlahBeli`, `TotalDiskon`, `Total`) "
            + "VALUES ('"+txt_pembeli.getText()+"', '"+cbo_merk.getSelectedItem()+"', '"+cbo_processor.getSelectedItem()+"', "
            + "'"+txt_jumlahbarang.getText()+"', '"+txt_totaldiskon.getText()+"', '"+txt_total.getText()+"')";
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
            } else {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }             
          }
    }//GEN-LAST:event_btn_addbtn_nextActionPerformed

    private void btn_refreshbtn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshbtn_beliActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btn_refreshbtn_beliActionPerformed

    private void btn_deletebtn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletebtn_beliActionPerformed
        // TODO add your handling code here:
        int baris = Tbl_Data.getSelectedRow();
        if (baris != -1){
            String a = Tbl_Data.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM data_laptop WHERE NamaPembeli='"+a+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
            } else {
                    JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_deletebtn_beliActionPerformed

    private void cbo_processorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_processorActionPerformed
        // TODO add your handling code here:
        if(txt_pembeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Isi Merk Terlebih Dahulu!!!");
        }else{
        
        if(cbo_processor.getSelectedItem().equals("Intel Core i3"))
        {
          txt_harga.setText(String.valueOf(i3));
        } else

        if (cbo_processor.getSelectedItem().equals("Intel Core i5"))
        {
            txt_harga.setText(String.valueOf(i5));
        } else

        if (cbo_processor.getSelectedItem().equals("Intel Core i7"))
        {
            txt_harga.setText(String.valueOf(i7));
        }
        }
    }//GEN-LAST:event_cbo_processorActionPerformed

    private void cbo_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_merkActionPerformed
        // TODO add your handling code here:
        if(txt_pembeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Isi Nama Terlebih Dahulu!!!");
        }
        
        if(cbo_merk.getSelectedItem().equals("Acer"))
        {
            i7 = 10000000;
            i5 = 7800000;
            i3 = 5300000;
        } else

        if (cbo_merk.getSelectedItem().equals("Asus"))
        {
            i7 = 92000000;
            i5 = 6800000;
            i3 = 5000000;
        } else

        if (cbo_merk.getSelectedItem().equals("Lenovo"))
        {
            i7 = 12000000;
            i5 = 8400000;
            i3 = 5500000;
        }
    }//GEN-LAST:event_cbo_merkActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_txt_cariKeyReleased

    private void cbo_jenisbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_jenisbayarActionPerformed
        // TODO add your handling code here:
        if(txt_jumlahbarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Isi Jumlah Barang Yang Ingin Dibeli!!!");
        }
        
            jumlahbarang = Integer.parseInt(txt_jumlahbarang.getText());
            
        {
        if(cbo_merk.getSelectedItem().equals("Acer") && cbo_jenisbayar.getSelectedItem().equals("Cash"))
        {
           if (jumlahbarang <=5){
            diskon = 0;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }else
           if (jumlahbarang >=6){
            diskon = 5;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }
        } else
        if(cbo_merk.getSelectedItem().equals("Acer") && cbo_jenisbayar.getSelectedItem().equals("Transfer"))
        {
            if (jumlahbarang <=5){
            diskon = 0;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }else
           if (jumlahbarang >=6){
            diskon = 4;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }
        } else
         
            
        if(cbo_merk.getSelectedItem().equals("Asus") && cbo_jenisbayar.getSelectedItem().equals("Cash"))
        {
            if (jumlahbarang <=5){
            diskon = 0;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }else
           if (jumlahbarang >=6){
            diskon = 5;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }
        } else

        if(cbo_merk.getSelectedItem().equals("Asus") && cbo_jenisbayar.getSelectedItem().equals("Transfer"))
        {
            if (jumlahbarang <=5){
            diskon = 0;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }else
           if (jumlahbarang >=6){
            diskon = 4;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }
        }
        else
                        
        if(cbo_merk.getSelectedItem().equals("Lenovo") && cbo_jenisbayar.getSelectedItem().equals("Cash"))
        {
            if (jumlahbarang <=5){
            diskon = 0;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }else
           if (jumlahbarang >=6){
            diskon = 5;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }
        } else
        if(cbo_merk.getSelectedItem().equals("Lenovo") && cbo_jenisbayar.getSelectedItem().equals("Transfer"))
        {
            if (jumlahbarang <=5){
            diskon = 0;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }else
           if (jumlahbarang >=6){
            diskon = 4;
            txt_diskon.setText(String.valueOf(diskon)+"%");
                    }
        }

        harga = Integer.parseInt(txt_harga.getText());
        //diskon = Integer.parseInt(txt_diskon.getText());
        jumlahbarang = Integer.parseInt(txt_jumlahbarang.getText());
        totaldiskon = (harga*diskon)/100;
        txt_totaldiskon.setText(String.valueOf(totaldiskon));
        txt_totalbarang.setText(String.valueOf(jumlahbarang));
        total = (harga-totaldiskon)*jumlahbarang;
        txt_total.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_cbo_jenisbayarActionPerformed

    private void cbo_merkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbo_merkKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_merkKeyReleased

    private void cbo_processorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbo_processorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_processorKeyReleased

    private void cbo_jenisbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbo_jenisbayarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_jenisbayarKeyReleased

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBOII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBOII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBOII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBOII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PBOII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_Data;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_refresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_jenisbayar;
    private javax.swing.JComboBox<String> cbo_merk;
    private javax.swing.JComboBox<String> cbo_processor;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_diskon;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlahbarang;
    private javax.swing.JTextField txt_pembeli;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_totalbarang;
    private javax.swing.JTextField txt_totaldiskon;
    // End of variables declaration//GEN-END:variables
}
